version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: suitebusiness-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: suitebusiness_user
      POSTGRES_PASSWORD: suitebusiness_dev_password
      POSTGRES_DB: suitebusiness
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U suitebusiness_user -d suitebusiness"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Adminer for database management UI
  adminer:
    image: adminer:latest
    container_name: suitebusiness-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    name: suitebusiness_postgres_data
